[package]
name = "vocab_trainer"
version = "0.0.0"
edition = "2021"
resolver = "2"

[dependencies]
rustyline = { git = "https://github.com/kkawakam/rustyline" }
rustyline-derive = { git = "https://github.com/kkawakam/rustyline" }
termion = "1.5.6"

[[bin]]
name = "main"
path = "src/main.rs"
